// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MailIndexImport } from './routes/mail/index'
import { Route as ProfileCreateImport } from './routes/profile/create'
import { Route as AuthSignInImport } from './routes/auth/sign-in'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MailIndexRoute = MailIndexImport.update({
  path: '/mail/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileCreateRoute = ProfileCreateImport.update({
  path: '/profile/create',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/profile/create': {
      preLoaderRoute: typeof ProfileCreateImport
      parentRoute: typeof rootRoute
    }
    '/mail/': {
      preLoaderRoute: typeof MailIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthSignInRoute,
  ProfileCreateRoute,
  MailIndexRoute,
])
