// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileCreateImport } from './routes/profile/create'
import { Route as MailLayoutImport } from './routes/mail/_layout'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as MailInboxIndexImport } from './routes/mail/inbox/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileCreateRoute = ProfileCreateImport.update({
  path: '/profile/create',
  getParentRoute: () => rootRoute,
} as any)

const MailLayoutRoute = MailLayoutImport.update({
  path: '/mail/layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const MailInboxIndexRoute = MailInboxIndexImport.update({
  path: '/mail/inbox/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/mail/_layout': {
      preLoaderRoute: typeof MailLayoutImport
      parentRoute: typeof rootRoute
    }
    '/profile/create': {
      preLoaderRoute: typeof ProfileCreateImport
      parentRoute: typeof rootRoute
    }
    '/mail/inbox/': {
      preLoaderRoute: typeof MailInboxIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthSignInRoute,
  MailLayoutRoute,
  ProfileCreateRoute,
  MailInboxIndexRoute,
])
