/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MailImport } from './routes/_mail'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileCreateImport } from './routes/profile/create'
import { Route as AuthSignInImport } from './routes/auth/sign-in'
import { Route as MailMailInboxImport } from './routes/_mail/mail/inbox'

// Create/Update Routes

const MailRoute = MailImport.update({
  id: '/_mail',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileCreateRoute = ProfileCreateImport.update({
  path: '/profile/create',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const MailMailInboxRoute = MailMailInboxImport.update({
  path: '/mail/inbox',
  getParentRoute: () => MailRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_mail': {
      preLoaderRoute: typeof MailImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/profile/create': {
      preLoaderRoute: typeof ProfileCreateImport
      parentRoute: typeof rootRoute
    }
    '/_mail/mail/inbox': {
      preLoaderRoute: typeof MailMailInboxImport
      parentRoute: typeof MailImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  MailRoute.addChildren([MailMailInboxRoute]),
  AuthSignInRoute,
  ProfileCreateRoute,
])

/* prettier-ignore-end */
